# Generated by Django 2.0.3 on 2018-04-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_bio',
        ),
    ]
